"""Streamlit human review console MVP for TicketPilot.

Provides a UI for human reviewers to review, approve, edit, escalate, or
reject draft replies generated by the TicketPilot pipeline.
"""

import json

import streamlit as st

from ticketpilot.confidence.scorer import ConfidenceBreakdown, ConfidenceLevel
from ticketpilot.degradation.router import DegradedResponse, ResponseStrategy
from ticketpilot.drafting.generator import DraftGenerationResult
from ticketpilot.drafting.pipeline import run_pipeline_with_draft
from ticketpilot.drafting.schemas import DraftedTicketResult
from ticketpilot.pipeline import post_process
from ticketpilot.review.schemas import ReviewAction, ReviewDecision
from ticketpilot.review.store import ReviewStore
from ticketpilot.review.retrieval_viz import render_retrieval_trace
from ticketpilot.schema.ticket import RawTicket, RiskSeverity

DEMO_TICKET_JSON = json.dumps(
    {
        "original_text": "我要退款，订单号是 12345，请帮我处理。",
        "submitted_at": "2026-05-02T10:00:00",
        "customer_id": "cust-001",
    },
    ensure_ascii=False,
    indent=2,
)

DEFAULT_STORE_PATH = "reviews.jsonl"


# ---------------------------------------------------------------------------
# DraftGenerationResult → ReviewDecision audit field converter
# ---------------------------------------------------------------------------


def draft_gen_to_audit_fields(
    gen_result: DraftGenerationResult | None,
) -> dict:
    """Convert DraftGenerationResult to compact audit field dict.

    Extracts fields suitable for ReviewDecision.draft_audit without
    including full prompts, API keys, or draft text.

    Args:
        gen_result: DraftGenerationResult from Phase 11.6 generator.
            May be None for older pipelines.

    Returns:
        Dict with audit fields. All values are serializable.
        Returns empty dict if gen_result is None.
    """
    if gen_result is None:
        return {}

    draft = gen_result.draft
    cv = gen_result.citation_validation
    gr = gen_result.guard_result

    # Build human_review_reasons from trace
    reasons: list[str] = []
    if draft.fallback_reason:
        reasons.append(f"fallback:{draft.fallback_reason}")
    if draft.escalation_reason:
        reasons.append(f"escalation:{draft.escalation_reason}")
    if draft.unsupported_claims:
        reasons.append("unsupported_claims")
    if cv and not cv.is_valid:
        reasons.append("citation_validation_failed")
    if cv and cv.must_human_review:
        reasons.append("citation_validation_human_review")
    if gr and not gr.guard_passed:
        reasons.append("guard_failed")
        if gr.has_uncited_claims:
            reasons.append("uncited_claims")
        if gr.has_forbidden_promise:
            reasons.append("forbidden_promise")
        if not gr.risk_flags_respected:
            reasons.append("risk_not_acknowledged")

    return {
        "provider_name": gen_result.provider_name,
        "model_name": gen_result.model_name,
        "citation_validation_valid": cv.is_valid if cv else None,
        "valid_cited_evidence_ids": (
            cv.valid_cited_evidence_ids if cv else []
        ),
        "invalid_cited_evidence_ids": (
            cv.invalid_cited_evidence_ids if cv else []
        ),
        "missing_citation_required": cv.missing_citation_required if cv else None,
        "guard_passed": gr.guard_passed if gr else None,
        "guard_uncited_claims": gr.has_uncited_claims if gr else None,
        "guard_forbidden_promise": gr.has_forbidden_promise if gr else None,
        "guard_forbidden_details": gr.forbidden_promise_details if gr else [],
        "guard_risk_not_acknowledged": (
            not gr.risk_flags_respected if gr else None
        ),
        "human_review_forced": draft.must_human_review,
        "human_review_reasons": sorted(set(reasons)),
        "escalation_reason": draft.escalation_reason,
    }


# ---------------------------------------------------------------------------
# Trigger reason detection
# ---------------------------------------------------------------------------


def determine_trigger_reasons(result: DraftedTicketResult) -> list[str]:
    """Determine review trigger reasons from a DraftedTicketResult.

    Inspects the draft reply and risk assessment to identify why the
    ticket was flagged for human review.

    Returns:
        Sorted list of unique trigger reason strings from:
        "high_risk", "unsupported_claims", "no_evidence", "generation_error"
    """
    reasons: list[str] = []
    draft = result.draft_reply
    risk = result.ticket_output.risk_assessment

    # Check high risk — ticket flagged by risk assessment
    if risk.must_human_review or risk.severity == RiskSeverity.HIGH:
        reasons.append("high_risk")

    # Check no-evidence fallback — draft was generated without any evidence
    if draft.fallback_reason == "no_evidence":
        reasons.append("no_evidence")

    # Check unsupported claims — draft has claims not backed by evidence
    if draft.unsupported_claims:
        reasons.append("unsupported_claims")

    # Check generation error — draft generation itself failed
    if draft.fallback_reason == "generation_error":
        reasons.append("generation_error")

    return reasons


def build_review_decision(
    result: DraftedTicketResult,
    action: ReviewAction,
    edited_text: str | None = None,
    decision_reason: str = "",
    gen_result: DraftGenerationResult | None = None,
    confidence: ConfidenceBreakdown | None = None,
    degraded: DegradedResponse | None = None,
) -> ReviewDecision:
    """Build a ReviewDecision from a DraftedTicketResult and review action.

    Args:
        result: The pipeline output containing ticket_output and draft_reply.
        action: The action the reviewer took.
        edited_text: Edited draft text (required for EDIT action).
        decision_reason: Reason for escalation or rejection.
        gen_result: Optional DraftGenerationResult from Phase 11.6 generator.
            When provided, audit fields are populated from the generation result.
            When None (older pipelines), audit fields remain unset (None/[]).

    Returns:
        A fully populated ReviewDecision ready to be persisted.
    """
    ticket_output = result.ticket_output
    draft = result.draft_reply
    risk = ticket_output.risk_assessment

    citations_summary = [
        {"chunk_id": str(c.chunk_id), "doc_type": c.doc_type.value}
        for c in draft.citations
    ]

    # Extract audit fields from DraftGenerationResult if available
    audit = draft_gen_to_audit_fields(gen_result)

    return ReviewDecision(
        ticket_id=ticket_output.ticket_id,
        ticket_text=ticket_output.normalized_ticket.text,
        action=action,
        edited_text=edited_text,
        decision_reason=decision_reason,
        original_draft_text=draft.draft_text,
        confidence=draft.confidence,
        had_unsupported_claims=bool(draft.unsupported_claims),
        was_high_risk=bool(
            risk.must_human_review or risk.severity == RiskSeverity.HIGH
        ),
        intent=ticket_output.classification.intent.value,
        risk_flags=[f.value for f in risk.flags],
        citations_summary=citations_summary,
        evidence_used_count=len(draft.evidence_used),
        review_trigger_reasons=determine_trigger_reasons(result),
        reviewer_label="",
        # Audit fields from DraftGenerationResult
        provider_name=audit.get("provider_name"),
        model_name=audit.get("model_name"),
        citation_validation_valid=audit.get("citation_validation_valid"),
        valid_cited_evidence_ids=audit.get("valid_cited_evidence_ids", []),
        invalid_cited_evidence_ids=audit.get("invalid_cited_evidence_ids", []),
        missing_citation_required=audit.get("missing_citation_required"),
        guard_passed=audit.get("guard_passed"),
        guard_uncited_claims=audit.get("guard_uncited_claims"),
        guard_forbidden_promise=audit.get("guard_forbidden_promise"),
        guard_forbidden_details=audit.get("guard_forbidden_details", []),
        guard_risk_not_acknowledged=audit.get("guard_risk_not_acknowledged"),
        human_review_forced=audit.get("human_review_forced"),
        human_review_reasons=audit.get("human_review_reasons", []),
        escalation_reason=audit.get("escalation_reason"),
        # Confidence breakdown
        confidence_level=confidence.level.value if confidence else None,
        confidence_retrieval=confidence.retrieval_confidence if confidence else None,
        confidence_classification=confidence.classification_confidence if confidence else None,
        confidence_citation=confidence.citation_confidence if confidence else None,
        confidence_evidence_density=confidence.evidence_density if confidence else None,
        response_strategy=degraded.strategy.value if degraded else None,
    )


def _parse_raw_ticket(json_str: str) -> RawTicket:
    """Parse a JSON string into a RawTicket.

    The JSON should contain fields matching the RawTicket schema:
    ``original_text`` (str), ``submitted_at`` (ISO datetime string),
    and optionally ``customer_id`` (str).

    Strips whitespace around input.  Empty input or invalid JSON
    raises ``ValueError`` with a Chinese user-facing message.
    """
    stripped = json_str.strip()
    if not stripped:
        raise ValueError("请输入工单 JSON")
    try:
        data = json.loads(stripped)
    except json.JSONDecodeError:
        raise ValueError("请输入有效 JSON，示例格式见输入框。")
    return RawTicket.model_validate(data)


def _render_ticket_info(result: DraftedTicketResult) -> None:
    """Render ticket information, risk assessment, and evidence in the left column."""
    ticket_output = result.ticket_output
    draft = result.draft_reply

    st.subheader("工单信息")
    st.write(f"**工单 ID:** {ticket_output.ticket_id}")
    st.write(f"**归一化文本:** {ticket_output.normalized_ticket.text}")
    st.write(
        f"**问题类型:** {ticket_output.classification.intent.value} "
        f"(置信度: {ticket_output.classification.confidence:.2f})"
    )

    st.subheader("风险评估")
    risk = ticket_output.risk_assessment
    severity_colors = {"high": "red", "medium": "orange", "low": "green"}
    sev_color = severity_colors.get(risk.severity.value, "grey")
    st.markdown(
        f"**严重程度:** <span style='color:{sev_color}'>{risk.severity.value}</span>",
        unsafe_allow_html=True,
    )
    st.write(
        f"**风险标志:** {', '.join(f.value for f in risk.flags) if risk.flags else '无'}"
    )

    must_review = risk.must_human_review
    review_color = "red" if must_review else "green"
    st.markdown(
        f"**必须人工审核:** <span style='color:{review_color};font-weight:bold'>"
        f"{'是' if must_review else '否'}</span>",
        unsafe_allow_html=True,
    )

    st.subheader("证据候选")
    if ticket_output.evidence_candidates:
        for i, ev in enumerate(ticket_output.evidence_candidates):
            title = ev.title or ev.doc_type.value
            with st.expander(f"证据 {i + 1}: {title}"):
                st.write(f"**来源:** {ev.source_table}")
                st.write(f"**得分:** {ev.score:.4f}")
                st.write(f"**摘录:** {ev.content[:200]}")
    else:
        st.write("无可用证据")

    st.subheader("缺失信息")
    if draft.missing_information:
        for info in draft.missing_information:
            st.write(f"- {info}")
    else:
        st.write("无")


def _render_draft_and_actions(result: DraftedTicketResult) -> None:
    """Render draft reply, citations, and review action buttons in the right column."""
    draft = result.draft_reply

    st.subheader("草稿回复")
    st.text_area(
        "草稿文本",
        draft.draft_text,
        height=200,
        key="draft_text_display",
        disabled=True,
    )

    # Fallback warnings
    if draft.fallback_reason == "no_evidence":
        st.warning("无证据回退 — 回复未基于实际证据")
    if draft.fallback_reason == "generation_error":
        st.error("生成异常 — 草稿生成过程中发生错误")
    if draft.unsupported_claims:
        with st.expander("无证据支持的声明"):
            for claim in draft.unsupported_claims:
                st.write(f"- {claim}")

    st.subheader("引用")
    if draft.citations:
        for i, c in enumerate(draft.citations):
            st.write(f"{i + 1}. chunk_id: `{c.chunk_id}`, 类型: {c.doc_type.value}")
    else:
        st.write("无引用")

    # --- Guard status display (Phase 11) ---
    # Display guard/citation info when DraftGenerationResult is available
    # via session state (set by pipeline integration in Phase 11.6+)
    gen_result: DraftGenerationResult | None = getattr(
        st.session_state, "gen_result", None
    )
    if gen_result is not None:
        st.subheader("生成状态")
        cv = gen_result.citation_validation
        gr = gen_result.guard_result
        col_p, col_g = st.columns(2)
        with col_p:
            st.write(f"**提供商:** {gen_result.provider_name}")
            if cv:
                valid_color = "green" if cv.is_valid else "red"
                st.markdown(
                    f"**引用验证:** <span style='color:{valid_color}'>"
                    f"{'通过' if cv.is_valid else '失败'}</span>",
                    unsafe_allow_html=True,
                )
                if cv.invalid_cited_evidence_ids:
                    st.write(f"无效引用: {', '.join(cv.invalid_cited_evidence_ids)}")
                if cv.missing_citation_required:
                    st.warning("存在可能无引用的声明")
        with col_g:
            if gr:
                guard_color = "green" if gr.guard_passed else "red"
                st.markdown(
                    f"**护卫检查:** <span style='color:{guard_color}'>"
                    f"{'通过' if gr.guard_passed else '失败'}</span>",
                    unsafe_allow_html=True,
                )
                if gr.has_forbidden_promise:
                    st.error(f"禁止承诺: {', '.join(gr.forbidden_promise_details)}")
                if gr.has_uncited_claims:
                    st.warning("存在无引用的声明")
                if not gr.risk_flags_respected:
                    st.warning("高风险标记未在草稿中确认")

        # Human review reasons
        reasons = draft_gen_to_audit_fields(gen_result).get("human_review_reasons", [])
        if reasons:
            st.write(f"**人工审核原因:** {', '.join(reasons)}")

        # Escalation reason
        if draft.escalation_reason:
            st.write(f"**升级原因:** {draft.escalation_reason}")

    # --- Confidence Breakdown & Degradation Strategy (new) ---
    confidence: ConfidenceBreakdown | None = getattr(
        st.session_state, "confidence", None
    )
    degraded: DegradedResponse | None = getattr(
        st.session_state, "degraded", None
    )

    if confidence and degraded:
        st.subheader("置信度分析")

        # Overall score with color
        level_colors = {
            ConfidenceLevel.HIGH: "green",
            ConfidenceLevel.MEDIUM: "orange",
            ConfidenceLevel.LOW: "red",
            ConfidenceLevel.CRITICAL: "red",
        }
        level_labels = {
            ConfidenceLevel.HIGH: "高置信",
            ConfidenceLevel.MEDIUM: "中置信",
            ConfidenceLevel.LOW: "低置信",
            ConfidenceLevel.CRITICAL: "极低置信",
        }
        color = level_colors.get(confidence.level, "grey")
        label = level_labels.get(confidence.level, "未知")

        st.markdown(
            f"**综合置信度:** {confidence.overall:.2f} "
            f"<span style='color:{color};font-weight:bold'>({label})</span>",
            unsafe_allow_html=True,
        )

        # 4-dimension breakdown
        col_r, col_c = st.columns(2)
        with col_r:
            st.write(f"🔍 检索置信度: {confidence.retrieval_confidence:.2f}")
            st.write(f"📊 分类置信度: {confidence.classification_confidence:.2f}")
        with col_c:
            st.write(f"📎 引用覆盖度: {confidence.citation_confidence:.2f}")
            st.write(f"📦 证据密度: {confidence.evidence_density:.2f}")

        # Strategy display
        st.subheader("回复策略")
        strategy_labels = {
            ResponseStrategy.AUTO_SEND: ("✅ 自动发送", "green"),
            ResponseStrategy.AUTO_SEND_CAUTIOUS: ("⚠️ 自动发送（含免责声明）", "orange"),
            ResponseStrategy.HUMAN_REVIEW: ("👤 需人工审核", "orange"),
            ResponseStrategy.HUMAN_ESCALATION: ("🚨 直接转人工", "red"),
        }
        strat_label, strat_color = strategy_labels.get(
            degraded.strategy, ("未知", "grey")
        )
        st.markdown(
            f"**策略:** <span style='color:{strat_color};font-weight:bold'>"
            f"{strat_label}</span>",
            unsafe_allow_html=True,
        )

        if degraded.disclaimer:
            st.warning(f"免责声明: {degraded.disclaimer}")
        if degraded.escalation_reason:
            st.error(f"升级原因: {degraded.escalation_reason}")

    # --- Provenance display (if available) ---
    provenance = getattr(draft, "provenance", None)
    if provenance and provenance.claims:
        st.subheader("溯源链")
        for claim in provenance.claims:
            st.write(
                f"[{claim.citation_index}] \"{claim.claim_text[:50]}\" "
                f"← chunk `{str(claim.source_chunk_id)[:8]}...` "
                f"({claim.source_doc_type}, {claim.retrieval_method}, "
                f"score={claim.retrieval_score:.2f})"
            )

    st.subheader("审核操作")

    col1, col2 = st.columns(2)

    with col1:
        if st.button("批准", key="approve_btn", type="primary"):
            _save_and_display(result, ReviewAction.APPROVE)

        if st.button("编辑", key="edit_btn"):
            st.session_state.show_edit = True

    with col2:
        if st.button("升级", key="escalate_btn"):
            st.session_state.show_escalate = True

        if st.button("拒绝", key="reject_btn"):
            st.session_state.show_reject = True

    # Edit section
    if st.session_state.get("show_edit"):
        edited = st.text_area("编辑草稿", draft.draft_text, height=150, key="edit_text")
        if st.button("保存编辑", key="save_edit_btn"):
            if edited.strip():
                _save_and_display(result, ReviewAction.EDIT, edited_text=edited)
            else:
                st.error("编辑后的文本不能为空")

    # Escalate section
    if st.session_state.get("show_escalate"):
        reason = st.text_input("升级原因", key="escalate_reason")
        if st.button("确认升级", key="confirm_escalate_btn"):
            if reason.strip():
                _save_and_display(
                    result, ReviewAction.ESCALATE, decision_reason=reason
                )
            else:
                st.error("请输入升级原因")

    # Reject section
    if st.session_state.get("show_reject"):
        reason = st.text_input("拒绝原因", key="reject_reason")
        if st.button("确认拒绝", key="confirm_reject_btn"):
            if reason.strip():
                _save_and_display(
                    result, ReviewAction.REJECT, decision_reason=reason
                )
            else:
                st.error("请输入拒绝原因")


def _save_and_display(
    result: DraftedTicketResult,
    action: ReviewAction,
    edited_text: str | None = None,
    decision_reason: str = "",
) -> None:
    """Build a ReviewDecision, persist it, and show a success message."""
    confidence = getattr(st.session_state, "confidence", None)
    degraded = getattr(st.session_state, "degraded", None)
    decision = build_review_decision(
        result, action, edited_text, decision_reason,
        confidence=confidence, degraded=degraded,
    )
    store = ReviewStore(DEFAULT_STORE_PATH)
    store.save(decision)
    total = store.count()
    st.success(f"审核已保存！审核 ID: {decision.review_id}")
    st.info(f"总审核记录数: {total}")


def main() -> None:
    """Main entrypoint for the Streamlit review console."""
    st.set_page_config(page_title="TicketPilot 审核控制台", layout="wide")

    st.title("TicketPilot 审核控制台")
    st.caption("分级策略: 高/中置信自动发送 | 低置信人工审核 | 极低置信转人工")

    # Initialize session state flags
    if "result" not in st.session_state:
        st.session_state.result = None
    if "show_edit" not in st.session_state:
        st.session_state.show_edit = False
    if "show_escalate" not in st.session_state:
        st.session_state.show_escalate = False
    if "show_reject" not in st.session_state:
        st.session_state.show_reject = False

    # Input section
    st.header("输入工单")
    input_json = st.text_area(
        "工单 JSON",
        value=DEMO_TICKET_JSON,
        height=150,
    )

    if st.button("处理工单", type="primary"):
        try:
            raw_ticket = _parse_raw_ticket(input_json)
            with st.spinner("正在处理工单..."):
                result = run_pipeline_with_draft(raw_ticket)
            st.session_state.result = result
            # Compute confidence breakdown and degradation strategy
            confidence, degraded = post_process(
                result.ticket_output, result.draft_reply
            )
            st.session_state.confidence = confidence
            st.session_state.degraded = degraded
            st.success("工单处理完成")
        except ValueError as e:
            st.error(str(e))
        except Exception as e:
            st.error(f"处理失败: {e}")

    # Display results if available
    if st.session_state.result:
        result = st.session_state.result

        col_left, col_right = st.columns(2)

        with col_left:
            _render_ticket_info(result)

        with col_right:
            _render_draft_and_actions(result)

        # Retrieval trace visualization (when available)
        retrieval_trace = getattr(result.ticket_output, "retrieval_trace", None)
        if retrieval_trace is not None:
            with st.expander("Retrieval Trace", expanded=False):
                render_retrieval_trace(retrieval_trace)
    else:
        st.info("请粘贴工单 JSON 并点击「处理工单」")


if __name__ == "__main__":
    main()
