"""Streamlit human review console MVP for TicketPilot.

Provides a UI for human reviewers to review, approve, edit, escalate, or
reject draft replies generated by the TicketPilot pipeline.
"""

import json

import streamlit as st

from ticketpilot.drafting.pipeline import run_pipeline_with_draft
from ticketpilot.drafting.schemas import DraftedTicketResult
from ticketpilot.review.schemas import ReviewAction, ReviewDecision
from ticketpilot.review.store import ReviewStore
from ticketpilot.schema.ticket import RawTicket, RiskSeverity

DEMO_TICKET_JSON = json.dumps(
    {
        "original_text": "我要退款，订单号是 12345，请帮我处理。",
        "submitted_at": "2026-05-02T10:00:00",
        "customer_id": "cust-001",
    },
    ensure_ascii=False,
    indent=2,
)

DEFAULT_STORE_PATH = "reviews.jsonl"


def determine_trigger_reasons(result: DraftedTicketResult) -> list[str]:
    """Determine review trigger reasons from a DraftedTicketResult.

    Inspects the draft reply and risk assessment to identify why the
    ticket was flagged for human review.

    Returns:
        Sorted list of unique trigger reason strings from:
        "high_risk", "unsupported_claims", "no_evidence", "generation_error"
    """
    reasons: list[str] = []
    draft = result.draft_reply
    risk = result.ticket_output.risk_assessment

    # Check high risk — ticket flagged by risk assessment
    if risk.must_human_review or risk.severity == RiskSeverity.HIGH:
        reasons.append("high_risk")

    # Check no-evidence fallback — draft was generated without any evidence
    if draft.fallback_reason == "no_evidence":
        reasons.append("no_evidence")

    # Check unsupported claims — draft has claims not backed by evidence
    if draft.unsupported_claims:
        reasons.append("unsupported_claims")

    # Check generation error — draft generation itself failed
    if draft.fallback_reason == "generation_error":
        reasons.append("generation_error")

    return reasons


def build_review_decision(
    result: DraftedTicketResult,
    action: ReviewAction,
    edited_text: str | None = None,
    decision_reason: str = "",
) -> ReviewDecision:
    """Build a ReviewDecision from a DraftedTicketResult and review action.

    Args:
        result: The pipeline output containing ticket_output and draft_reply.
        action: The action the reviewer took.
        edited_text: Edited draft text (required for EDIT action).
        decision_reason: Reason for escalation or rejection.

    Returns:
        A fully populated ReviewDecision ready to be persisted.
    """
    ticket_output = result.ticket_output
    draft = result.draft_reply
    risk = ticket_output.risk_assessment

    citations_summary = [
        {"chunk_id": str(c.chunk_id), "doc_type": c.doc_type.value}
        for c in draft.citations
    ]

    return ReviewDecision(
        ticket_id=ticket_output.ticket_id,
        ticket_text=ticket_output.normalized_ticket.text,
        action=action,
        edited_text=edited_text,
        decision_reason=decision_reason,
        original_draft_text=draft.draft_text,
        confidence=draft.confidence,
        had_unsupported_claims=bool(draft.unsupported_claims),
        was_high_risk=bool(
            risk.must_human_review or risk.severity == RiskSeverity.HIGH
        ),
        intent=ticket_output.classification.intent.value,
        risk_flags=[f.value for f in risk.flags],
        citations_summary=citations_summary,
        evidence_used_count=len(draft.evidence_used),
        review_trigger_reasons=determine_trigger_reasons(result),
        reviewer_label="",
    )


def _parse_raw_ticket(json_str: str) -> RawTicket:
    """Parse a JSON string into a RawTicket.

    The JSON should contain fields matching the RawTicket schema:
    ``original_text`` (str), ``submitted_at`` (ISO datetime string),
    and optionally ``customer_id`` (str).

    Strips whitespace around input.  Empty input or invalid JSON
    raises ``ValueError`` with a Chinese user-facing message.
    """
    stripped = json_str.strip()
    if not stripped:
        raise ValueError("请输入工单 JSON")
    try:
        data = json.loads(stripped)
    except json.JSONDecodeError:
        raise ValueError("请输入有效 JSON，示例格式见输入框。")
    return RawTicket.model_validate(data)


def _render_ticket_info(result: DraftedTicketResult) -> None:
    """Render ticket information, risk assessment, and evidence in the left column."""
    ticket_output = result.ticket_output
    draft = result.draft_reply

    st.subheader("工单信息")
    st.write(f"**工单 ID:** {ticket_output.ticket_id}")
    st.write(f"**归一化文本:** {ticket_output.normalized_ticket.text}")
    st.write(
        f"**问题类型:** {ticket_output.classification.intent.value} "
        f"(置信度: {ticket_output.classification.confidence:.2f})"
    )

    st.subheader("风险评估")
    risk = ticket_output.risk_assessment
    severity_colors = {"high": "red", "medium": "orange", "low": "green"}
    sev_color = severity_colors.get(risk.severity.value, "grey")
    st.markdown(
        f"**严重程度:** <span style='color:{sev_color}'>{risk.severity.value}</span>",
        unsafe_allow_html=True,
    )
    st.write(
        f"**风险标志:** {', '.join(f.value for f in risk.flags) if risk.flags else '无'}"
    )

    must_review = risk.must_human_review
    review_color = "red" if must_review else "green"
    st.markdown(
        f"**必须人工审核:** <span style='color:{review_color};font-weight:bold'>"
        f"{'是' if must_review else '否'}</span>",
        unsafe_allow_html=True,
    )

    st.subheader("证据候选")
    if ticket_output.evidence_candidates:
        for i, ev in enumerate(ticket_output.evidence_candidates):
            title = ev.title or ev.doc_type.value
            with st.expander(f"证据 {i + 1}: {title}"):
                st.write(f"**来源:** {ev.source_table}")
                st.write(f"**得分:** {ev.score:.4f}")
                st.write(f"**摘录:** {ev.content[:200]}")
    else:
        st.write("无可用证据")

    st.subheader("缺失信息")
    if draft.missing_information:
        for info in draft.missing_information:
            st.write(f"- {info}")
    else:
        st.write("无")


def _render_draft_and_actions(result: DraftedTicketResult) -> None:
    """Render draft reply, citations, and review action buttons in the right column."""
    draft = result.draft_reply

    st.subheader("草稿回复")
    st.text_area(
        "草稿文本",
        draft.draft_text,
        height=200,
        key="draft_text_display",
        disabled=True,
    )

    # Fallback warnings
    if draft.fallback_reason == "no_evidence":
        st.warning("无证据回退 — 回复未基于实际证据")
    if draft.fallback_reason == "generation_error":
        st.error("生成异常 — 草稿生成过程中发生错误")
    if draft.unsupported_claims:
        with st.expander("无证据支持的声明"):
            for claim in draft.unsupported_claims:
                st.write(f"- {claim}")

    st.subheader("引用")
    if draft.citations:
        for i, c in enumerate(draft.citations):
            st.write(f"{i + 1}. chunk_id: `{c.chunk_id}`, 类型: {c.doc_type.value}")
    else:
        st.write("无引用")

    st.subheader("审核操作")

    col1, col2 = st.columns(2)

    with col1:
        if st.button("批准", key="approve_btn", type="primary"):
            _save_and_display(result, ReviewAction.APPROVE)

        if st.button("编辑", key="edit_btn"):
            st.session_state.show_edit = True

    with col2:
        if st.button("升级", key="escalate_btn"):
            st.session_state.show_escalate = True

        if st.button("拒绝", key="reject_btn"):
            st.session_state.show_reject = True

    # Edit section
    if st.session_state.get("show_edit"):
        edited = st.text_area("编辑草稿", draft.draft_text, height=150, key="edit_text")
        if st.button("保存编辑", key="save_edit_btn"):
            if edited.strip():
                _save_and_display(result, ReviewAction.EDIT, edited_text=edited)
            else:
                st.error("编辑后的文本不能为空")

    # Escalate section
    if st.session_state.get("show_escalate"):
        reason = st.text_input("升级原因", key="escalate_reason")
        if st.button("确认升级", key="confirm_escalate_btn"):
            if reason.strip():
                _save_and_display(
                    result, ReviewAction.ESCALATE, decision_reason=reason
                )
            else:
                st.error("请输入升级原因")

    # Reject section
    if st.session_state.get("show_reject"):
        reason = st.text_input("拒绝原因", key="reject_reason")
        if st.button("确认拒绝", key="confirm_reject_btn"):
            if reason.strip():
                _save_and_display(
                    result, ReviewAction.REJECT, decision_reason=reason
                )
            else:
                st.error("请输入拒绝原因")


def _save_and_display(
    result: DraftedTicketResult,
    action: ReviewAction,
    edited_text: str | None = None,
    decision_reason: str = "",
) -> None:
    """Build a ReviewDecision, persist it, and show a success message."""
    decision = build_review_decision(result, action, edited_text, decision_reason)
    store = ReviewStore(DEFAULT_STORE_PATH)
    store.save(decision)
    total = store.count()
    st.success(f"审核已保存！审核 ID: {decision.review_id}")
    st.info(f"总审核记录数: {total}")


def main() -> None:
    """Main entrypoint for the Streamlit review console."""
    st.set_page_config(page_title="TicketPilot 审核控制台", layout="wide")

    st.title("TicketPilot 审核控制台")
    st.caption("审核控制台 — 不自动发送回复")

    # Initialize session state flags
    if "result" not in st.session_state:
        st.session_state.result = None
    if "show_edit" not in st.session_state:
        st.session_state.show_edit = False
    if "show_escalate" not in st.session_state:
        st.session_state.show_escalate = False
    if "show_reject" not in st.session_state:
        st.session_state.show_reject = False

    # Input section
    st.header("输入工单")
    input_json = st.text_area(
        "工单 JSON",
        value=DEMO_TICKET_JSON,
        height=150,
    )

    if st.button("处理工单", type="primary"):
        try:
            raw_ticket = _parse_raw_ticket(input_json)
            with st.spinner("正在处理工单..."):
                result = run_pipeline_with_draft(raw_ticket)
            st.session_state.result = result
            st.success("工单处理完成")
        except ValueError as e:
            st.error(str(e))
        except Exception as e:
            st.error(f"处理失败: {e}")

    # Display results if available
    if st.session_state.result:
        result = st.session_state.result

        col_left, col_right = st.columns(2)

        with col_left:
            _render_ticket_info(result)

        with col_right:
            _render_draft_and_actions(result)
    else:
        st.info("请粘贴工单 JSON 并点击「处理工单」")


if __name__ == "__main__":
    main()
